### ISSUE TITLE
Pets List

### ISSUE THREAD

**Issue by pas0030376** [Rachelitaa/vetAppLove#2]
Pets are showing for everyone, even if u didnt add one, so if you add your pet EVERYONE will see it.

**Comment by zajustine** [comment]
i changed the .php for Pets and added a foreign key in Pets table, not working yet, as of now.

**Comment by zajustine** [comment]
fixed mostrarPets.php (rachelita's a big help) and it's returning only 1 row as of this moment.

**Comment by zajustine** [comment]
fixed
